In [1]:
import numpy as np


In [3]:
a=np.array([[1,2,4],[5,8,7]]) 
print("Array created using passed list.\n",a)

Array created using passed list.
 [[1 2 4]
 [5 8 7]]


In [4]:
b=np.zeros((3,4)) 
print("\nAn array initialized with all zeros: \n", b)



An array initialized with all zeros: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
 c=np.full ((3, 3), 6) 
print("nAn array initialized with all 6s.\n",c)


nAn array initialized with all 6s.
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [12]:
 d=np.random.random((2,2)) 
print("\nA random array.\n",d)


A random array.
 [[0.42469201 0.94139513]
 [0.21379544 0.03363029]]


In [17]:

e=np.arange(0, 30, 5)

print ("\nA sequential array with steps of 5:\n", e)



A sequential array with steps of 5:
 [ 0  5 10 15 20 25]


In [20]:
arr=np.array([[1, 2, 3, 4],[5, 2, 4, 2],[1,2,0,1]])

newarr=arr.reshape(4, 3)
print("\nOriginal array:\n",arr)

print ("Reshaped array(4,3):\n",newarr)




Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array(4,3):
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [21]:
flarr = arr.flatten()

print("\nOriginal array \n",arr)

print ("Fattened array:\n",flarr)



Original array 
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Fattened array:
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [24]:
print("\nNo. of dimensions:",arr.ndim)
print("\nShape of array: ",arr.shape)



No. of dimensions: 2

Shape of array:  (3, 4)


In [25]:
print("\nSize of array:",arr.size)


print("\nArray stores elements of type: ", arr.dtype)




Size of array: 12

Array stores elements of type:  int64


In [27]:
newtype=arr.astype('f')

print("\nConverted array elemnets:\n",newtype)

print("Converted array type:",newtype.dtype)


Converted array elemnets:
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]
Converted array type: float32
