In [1]:
import numpy as np

In [2]:
arr=np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])


In [3]:
print("original array:\n",arr)

original array:
 [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [4]:
print("\nevery other rows:",arr[0:3:2])


every other rows: [[-1.   2.   0.   4. ]
 [ 2.6  0.   7.   8. ]]


In [5]:
temp=arr[:2,:3];
print("\narray with",temp)


array with [[-1.   2.   0. ]
 [ 4.  -0.5  6. ]]


In [6]:
temp=arr[[0,1,2,3],[3,2,1,0]]
print("element:",temp)

element: [4. 6. 0. 3.]


In [8]:
cond=arr>2
temp=arr[cond]
print(temp)

[4.  4.  6.  2.6 7.  8.  3.  4. ]


In [9]:
arr=np.array([1,2,3,4,5,6,7])
print(arr)
print(arr[::2])

[1 2 3 4 5 6 7]
[1 3 5 7]


In [10]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print("\nOriginal arrays:\n",arr1,arr2)
print("\njoined array:\n",arr)


Original arrays:
 [1 2 3] [4 5 6]

joined array:
 [1 2 3 4 5 6]


In [11]:
arr=np.hstack((arr1,arr2))
print("\nHorizondal joining:\n",arr)


Horizondal joining:
 [1 2 3 4 5 6]


In [12]:
arr=np.vstack((arr1,arr2))
print("\nvertical joining:\n",arr)



vertical joining:
 [[1 2 3]
 [4 5 6]]


In [13]:
arr=np.dstack((arr1,arr2))
print("\nDepth joining:\n",arr)


Depth joining:
 [[[1 4]
  [2 5]
  [3 6]]]


In [15]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print("\n original array:\n",arr)
print("\n Spitted array:\n",newarr)


 original array:
 [1 2 3 4 5 6]

 Spitted array:
 [array([1, 2]), array([3, 4]), array([5, 6])]


In [16]:
print("\nSplitted array in another form:\n")
print(newarr[0])
print(newarr[1])
print(newarr[2])


Splitted array in another form:

[1 2]
[3 4]
[5 6]
